--!strict

local BAT_MODEL_NAME = "BatModel"
local FistConfig = require(script.Parent:WaitForChild("FistConfig"))
local CageConfig = require(script.Parent:WaitForChild("CageConfig"))
local TrashCanConfig = require(script.Parent:WaitForChild("TrashCanConfig"))

return table.freeze({
	BAT_MODEL_NAME = BAT_MODEL_NAME,
	WEAPON_MODEL_NAMES = table.freeze({
		FistConfig.WEAPON_MODEL_NAME,
		BAT_MODEL_NAME,
		CageConfig.WEAPON_MODEL_NAME,
		TrashCanConfig.WEAPON_MODEL_NAME,
	}),
	ATTACK_ANIMATION_NAME = "batattack",
	REMOTE_EVENT_NAME = "BatAttackRequest",
	KNOCKDOWN_ATTRIBUTE = "BatKnockedDown",
	HIT_EFFECT_TEMPLATE_NAME = "Punch",
	HIT_SOUND_TEMPLATE_NAME = "BetSound",

	ATTACK_COOLDOWN_SECONDS = 0.8,
	HIT_DELAY_SECONDS = 0.05,
	HIT_WINDOW_DURATION_SECONDS = 0.7,
	HANDLE_CONTACT_PADDING = 0.15,
	FALLBACK_HIT_RANGE_STUDS = 5,
	SERVER_RANGE_FORGIVENESS_MULTIPLIER = 1.12,
	FALLBACK_MAX_VERTICAL_DIFFERENCE = 4,
	MIN_TARGET_FORWARD_DOT = 0,
	KNOCKDOWN_DURATION_SECONDS = 1,
	INITIAL_KNOCKDOWN_TILT_DEGREES = 28,
	KNOCKBACK_SPEED = 15,
	KNOCKBACK_UPWARD_SPEED = 3,
	KNOCKBACK_TIP_SPEED = 1.5,
	KNOCKDOWN_COLLIDER_MIN_SIZE_STUDS = Vector3.new(2.2, 5, 1.4),
	KNOCKDOWN_COLLIDER_PADDING_STUDS = Vector3.new(0.12, 0.12, 0.12),
	KNOCKDOWN_COLLIDER_FRICTION = 0.25,
	KNOCKDOWN_COLLIDER_GROUND_CLEARANCE_STUDS = 0.05,

	HIT_EFFECT_FALLBACK_SIZE_STUDS = 3,
	HIT_EFFECT_MIN_SIZE_STUDS = 0.75,
	HIT_EFFECT_MAX_SIZE_STUDS = 8,
	HIT_EFFECT_HEIGHT_OFFSET_STUDS = 1,
	HIT_EFFECT_MAX_DISTANCE_STUDS = 80,
	HIT_EFFECT_LIFETIME_SECONDS = 0.45,
	HIT_EFFECT_FADE_SECONDS = 0.18,
})
