--!strict

return table.freeze({
	-- Models
	WEAPON_MODEL_NAME = "CageModel",
	TEMPLATE_MODEL_NAME = "cage",

	-- Forward capture sector (keeps the previous 0-4 stud effective range)
	AREA_MIN_DISTANCE = 0,
	AREA_MAX_DISTANCE = 4,
	AREA_FOV_DEGREES = 110,
	AREA_HEIGHT = 6,
	CAPTURE_PLACEMENT_DISTANCE = 2,

	-- Small server forgiveness for a highlighted target moving during network transit
	SERVER_DISTANCE_TOLERANCE = 0.75,
	SERVER_ANGLE_TOLERANCE_DEGREES = 8,
	SERVER_VERTICAL_TOLERANCE = 1,

	-- Local sector visual
	INDICATOR_SEGMENT_COUNT = 20,
	INDICATOR_THICKNESS = 0.05,
	INDICATOR_FILL_TRANSPARENCY = 0.88,
	INDICATOR_FILL_COLOR = Color3.fromRGB(255, 55, 55),
	INDICATOR_OUTLINE_WIDTH = 0.09,
	INDICATOR_OUTLINE_TRANSPARENCY = 0.2,
	INDICATOR_OUTLINE_COLOR = Color3.fromRGB(255, 35, 35),
	INDICATOR_GROUND_OFFSET = 0.02,

	-- Selected target visual
	TARGET_FILL_TRANSPARENCY = 0.82,
	TARGET_FILL_COLOR = Color3.fromRGB(255, 65, 65),
	TARGET_OUTLINE_TRANSPARENCY = 0,
	TARGET_OUTLINE_COLOR = Color3.fromRGB(255, 230, 230),

	-- Spawned cage placement
	FLOOR_CLEARANCE = 0.05,
	CAGE_DURATION_SECONDS = 2.5,

	-- Circular countdown above the cage
	TIMER_SEGMENT_COUNT = 12,
	TIMER_SIZE_PIXELS = 52,
	TIMER_RADIUS_PIXELS = 18,
	TIMER_SEGMENT_WIDTH_PIXELS = 4,
	TIMER_SEGMENT_HEIGHT_PIXELS = 10,
	TIMER_UPDATE_INTERVAL_SECONDS = 0.05,
	TIMER_ACTIVE_COLOR = Color3.fromRGB(255, 90, 55),
	TIMER_INACTIVE_COLOR = Color3.fromRGB(70, 28, 24),
	TIMER_HEIGHT_PADDING_STUDS = 0.75,

	-- Rescue prompt
	RESCUE_RADIUS = 3,
	RESCUE_HOLD_SECONDS = 4,
})
