--!strict

return table.freeze({
	GAME_PASS_ID = 1948226893,
	COOLDOWN_MULTIPLIER = 0.8,

	OWNED_ATTRIBUTE = "CooldownPassOwned",
	OWNERSHIP_READY_ATTRIBUTE = "CooldownPassOwnershipReady",
	TEST_OVERRIDE_ATTRIBUTE = "CooldownPassTestOverride",

	VIP_GAME_PASS_ID = 1952049145,
	VIP_CURRENCY_MULTIPLIER = 1.5,
	VIP_BONUS_CURRENCY = 5000,
	VIP_OWNED_ATTRIBUTE = "VIPPassOwned",
	VIP_OWNERSHIP_READY_ATTRIBUTE = "VIPPassOwnershipReady",
	VIP_BONUS_GRANTED_ATTRIBUTE = "VIPPassBonusGranted",

	X2_CASH_GAME_PASS_ID = 1955022559,
	X2_CASH_MULTIPLIER = 2,
	X2_CASH_OWNED_ATTRIBUTE = "X2CashPassOwned",
	X2_CASH_OWNERSHIP_READY_ATTRIBUTE = "X2CashPassOwnershipReady",

	SHOP_GUI_NAME = "ShopGui",
	SHOP_MAIN_FRAME_NAME = "ShopMainFrame",
	SCROLLING_FRAME_NAME = "ScrollingFrame",
	GAME_PASSES_FRAME_NAME = "GamePasses",
	COOLDOWN_PASS_FRAME_NAME = "CoolDownPass",
	COOLDOWN_BUY_BUTTON_NAME = "BuyCoolDownBtn",
	VIP_PASS_FRAME_NAME = "VIPPass",
	VIP_BUY_BUTTON_NAME = "BuyVIPBtn",
	X2_CASH_PASS_FRAME_NAME = "x2CashPass",
	X2_CASH_BUY_BUTTON_NAME = "x2CashBtn",
	THANKS_LABEL_NAME = "Thanks",

	ICONS_GUI_NAME = "IconsGui",
	PANEL_NAME = "CoolDownPass",
	BUY_BUTTON_NAME = "BuyCoolDownBtn",
	UI_BIND_TIMEOUT_SECONDS = 20,
	PURCHASE_GRANT_TIMEOUT_SECONDS = 15,

	OWNERSHIP_RETRY_INITIAL_SECONDS = 1,
	OWNERSHIP_RETRY_MAX_SECONDS = 30,
	PRODUCT_INFO_RETRY_SECONDS = 10,
})
