--!strict

return table.freeze({
	GAME_PASS_ID = 1948226893,
	COOLDOWN_MULTIPLIER = 0.8,

	OWNED_ATTRIBUTE = "CooldownPassOwned",
	OWNERSHIP_READY_ATTRIBUTE = "CooldownPassOwnershipReady",
	TEST_OVERRIDE_ATTRIBUTE = "CooldownPassTestOverride",

	ICONS_GUI_NAME = "IconsGui",
	PANEL_NAME = "VIPPassCoolDown",
	BUY_BUTTON_NAME = "BuyCoolDownBtn",
	UI_BIND_TIMEOUT_SECONDS = 20,
	PURCHASE_GRANT_TIMEOUT_SECONDS = 15,

	OWNERSHIP_RETRY_INITIAL_SECONDS = 1,
	OWNERSHIP_RETRY_MAX_SECONDS = 30,
	PRODUCT_INFO_RETRY_SECONDS = 10,
})
