--!strict

return table.freeze({
	SEARCH_SHAPE_VERSION = 2,
	SEARCH_SHAPE_VERSION_ATTRIBUTE = "SeekerSearchShapeVersion",
	SEARCH_RADIUS = 3,
	FORWARD_RADIUS_BONUS = 3,
	FORWARD_RAY_FRACTION = 1 / 4,
	MAX_VERTICAL_DIFFERENCE = 7,
	LINE_OF_SIGHT_HEIGHT = 1.5,
	SERVER_SCAN_INTERVAL = 0.1,
	CAGE_DURATION_SECONDS = 10,

	RESCUE_RADIUS = 3,
	RESCUE_HOLD_SECONDS = 0.75,
	POST_RESCUE_IMMUNITY_SECONDS = 2,

	CAGED_ATTRIBUTE = "SearchCaged",
	CAGED_UNTIL_ATTRIBUTE = "SearchCagedUntil",
	RESCUE_PROGRESS_ATTRIBUTE = "SearchRescueProgress",
	HIDER_INVISIBLE_ATTRIBUTE = "RoundHiderInvisible",
	PRESERVE_VISUAL_ATTRIBUTE = "RoundPreserveVisualWhenInvisible",

	VISUAL_RAY_COUNT = 64,
	VISUAL_UPDATE_INTERVAL = 1 / 30,
	VISUAL_WALL_PADDING = 0.1,
	VISUAL_FLOOR_OFFSET = 0.06,
	VISUAL_THICKNESS = 0.08,
	VISUAL_COLOR = Color3.fromRGB(255, 88, 28),
	VISUAL_TRANSPARENCY = 0.48,

	CAGED_COLOR = Color3.fromRGB(255, 205, 75),
	NORMAL_WALK_SPEED = 13,
})
