--!strict

return table.freeze({
	ROLE_HIDER = "Hider",
	ROLE_SEEKER = "Seeker",
	STARTING_PHASE = "Starting",
	ROUND_PHASE = "Round",
	START_STAGGER_MAX_SECONDS = 0.65,
	-- Keep turns responsive while softening abrupt direction changes at waypoints.
	NPC_TURN_RESPONSIVENESS = 35,
	NPC_TURN_MAX_ANGULAR_VELOCITY = 14,
	NPC_TURN_MAX_TORQUE = 10000000,

	MAP_CONTAINER_NAME = "Map",
	MAP_FLOOR_NAME = "Floor",
	MAP_WALLS_NAME = "Walls",
	MAX_ARENA_DISTANCE = 500,
	MIN_UP_VECTOR_Y = 0.98,
	MIN_GEOMETRY_SIZE = 0.05,
	GEOMETRY_EPSILON = 0.01,

	-- The largest NPC root is about three studs wide. Do not add an artificial
	-- comfort band: it made physically passable narrow corridors look closed.
	BODY_RADIUS = 1.5,
	SAFETY_MARGIN = 0,
	NODE_OUTSET = 0.04,
	NODE_MERGE_DISTANCE = 0.015,
	INTERSECTION_OUTSET_DIRECTIONS = 12,
	FLOOR_EDGE_CLEARANCE = 1.5,
	FLOOR_TARGET_EDGE_MARGIN = 1.5,
	FLOOR_SAMPLE_ATTEMPTS = 40,

	WANDER_SAMPLE_COUNT = 48,
	WANDER_PATH_CANDIDATE_LIMIT = 28,
	WANDER_CANDIDATES_PER_SECTOR = 2,
	WANDER_ABSOLUTE_MIN_TARGET_DISTANCE = 3,
	WANDER_MIN_TARGET_DISTANCE = 12,
	WANDER_SHORT_TARGET_PENALTY = 35,
	WANDER_DISTANCE_SCORE_CAP = 120,
	WANDER_FORWARD_WEIGHT = 32,
	WANDER_SCORE_RANDOMNESS = 18,
	WANDER_SECTOR_COUNT = 4,
	WANDER_UNVISITED_SECTOR_BONUS = 500,
	WANDER_REVISIT_RECOVERY_PER_SECOND = 4,
	WANDER_REVISIT_BONUS_CAP = 300,
	TARGET_RESERVATION_RADIUS = 10,
	TARGET_RESERVATION_PROXIMITY_PENALTY = 350,
	TARGET_RESERVATION_SECTOR_PENALTY = 260,

	-- A Hider enters Escape only after the Seeker has actually detected it in
	-- the vision cone. Normal wandering does not evaluate Seeker positions.
	FLEE_TRIGGER_DISTANCE = 12,
	FLEE_THREAT_CHECK_INTERVAL = 0.2,
	FLEE_RELEASE_DELAY = 0.8,
	FLEE_ROUTE_REPLAN_INTERVAL = 1.25,
	FLEE_DESTINATION_MIN_DISTANCE_GAIN = 5,
	FLEE_DISTANCE_GAIN_SCORE_CAP = 20,
	FLEE_DISTANCE_GAIN_WEIGHT = 24,
	FLEE_DISTANCE_SCORE_CAP = 45,
	FLEE_DISTANCE_WEIGHT = 5,
	FLEE_DANGER_DISTANCE = 12,
	FLEE_DANGER_PENALTY_PER_STUD = 40,
	FLEE_ROUTE_CANDIDATE_LIMIT = 4,
	FLEE_ROUTE_FIRST_GAIN_SCORE_CAP = 12,
	FLEE_ROUTE_FIRST_GAIN_WEIGHT = 30,
	FLEE_ROUTE_DANGER_PENALTY_PER_STUD = 70,
	FLEE_ROUTE_APPROACH_TOLERANCE = 1,

	-- The bot Seeker patrols wall corners and may only acquire human Hiders
	-- through its own vision cone and line of sight.
	SEEKER_PATROL_NODE_SAMPLE_COUNT = 8,
	SEEKER_PATROL_NODE_BONUS = 70,
	SEEKER_TARGET_SWITCH_ADVANTAGE = 3,
	SEEKER_EVIDENCE_CHECK_INTERVAL = 0.1,
	SEEKER_EVIDENCE_REPLAN_INTERVAL = 0.3,
	SEEKER_EVIDENCE_REPLAN_DISTANCE = 1.5,
	SEEKER_CHASE_MIN_SECONDS = 3,
	SEEKER_CHASE_MAX_SECONDS = 5,
	SEEKER_REACQUIRE_COOLDOWN_SECONDS = 1,
	-- Direct sight has a short, readable reaction beat before the chase. Patrol
	-- remains at RoundConfig.SEEKER_WALK_SPEED; only an active sight chase gets
	-- this speed multiplier and the more responsive initial turn.
	SEEKER_AGGRO_REACTION_SECONDS = 0.22,
	SEEKER_CHASE_SPEED_MULTIPLIER = 1.5,
	SEEKER_AGGRO_TURN_RESPONSIVENESS = 90,
	SEEKER_AGGRO_TURN_MAX_ANGULAR_VELOCITY = 40,
	SEEKER_AGGRO_SOUND_TEMPLATE_NAME = "HunterAggroSound",
	SEEKER_AGGRO_FALLBACK_SOUND_ID = "rbxasset://sounds/electronicpingshort.wav",
	SEEKER_AGGRO_SOUND_VOLUME = 1.1,
	SEEKER_AGGRO_SOUND_PLAYBACK_SPEED = 0.78,
	SEEKER_AGGRO_SOUND_ROLLOFF_MIN_DISTANCE = 4,
	SEEKER_AGGRO_SOUND_ROLLOFF_MAX_DISTANCE = 45,
	SEEKER_AGGRO_INDICATOR_MAX_DISTANCE = 60,
	SEEKER_AGGRO_INDICATOR_COLOR = Color3.fromRGB(255, 72, 48),
	SEEKER_AGGRO_INDICATOR_WIDTH = 48,
	SEEKER_AGGRO_INDICATOR_HEIGHT = 58,
	SEEKER_AGGRO_INDICATOR_MIN_HEIGHT = 4.5,
	SEEKER_AGGRO_INDICATOR_TOP_PADDING = 0.8,
	SEEKER_AGGRO_INDICATOR_POP_SECONDS = 0.1,
	SEEKER_AGGRO_INDICATOR_SETTLE_SECONDS = 0.12,

	ROUTE_PREFETCH_DISTANCE = 14,
	PREFETCH_RETRY_SECONDS = 0.35,
	ROUTE_RETRY_SECONDS = 0.1,
	WAYPOINT_REACHED_DISTANCE = 0.42,
	WAYPOINT_PLANE_THRESHOLD = 0.24,
	WAYPOINT_MAX_CROSS_TRACK = 1.25,
	PROGRESS_EPSILON = 0.08,
	STALL_SECONDS = 0.9,

	-- NPCs use the same physical gate proxy as players. When movement stops at
	-- a gate, a small impulse helps the server-owned Humanoid push the moving
	-- leaf instead of endlessly replanning into it.
	DOOR_INTERACTION_DELAY = 0.1,
	DOOR_INTERACTION_MAX_SECONDS = 1.8,
	DOOR_PUSH_INTERVAL = 0.15,
	DOOR_SERVER_OWNERSHIP_SECONDS = 1.25,
	DOOR_PROBE_FORWARD_OFFSET = 0.15,
	-- Includes the 1.5x Seeker proxy radius plus a small contact tolerance.
	DOOR_PROBE_RADIUS = 1.65,
	DOOR_PUSH_CONTACT_DISTANCE = 1.55,
	DOOR_PUSH_SPEED_CHANGE = 1,
	DOOR_PROBE_MAX_PARTS = 16,
})
