--!strict

return table.freeze({
	ROLE_HIDER = "Hider",
	ROLE_SEEKER = "Seeker",
	STARTING_PHASE = "Starting",
	ROUND_PHASE = "Round",
	START_STAGGER_MAX_SECONDS = 0.65,

	MAP_CONTAINER_NAME = "Map",
	MAP_FLOOR_NAME = "Floor",
	MAP_WALLS_NAME = "Walls",
	MAX_ARENA_DISTANCE = 500,
	MIN_UP_VECTOR_Y = 0.98,
	MIN_GEOMETRY_SIZE = 0.05,
	GEOMETRY_EPSILON = 0.01,

	-- Walls have two mathematical contours. Hard clearance reserves room for
	-- the NPC body; navigation clearance adds a deliberate safety margin.
	BODY_RADIUS = 1.6,
	SAFETY_MARGIN = 0.4,
	NODE_OUTSET = 0.14,
	NODE_MERGE_DISTANCE = 0.06,
	INTERSECTION_OUTSET_DIRECTIONS = 12,
	FLOOR_EDGE_CLEARANCE = 1.6,
	FLOOR_TARGET_EDGE_MARGIN = 1.6,
	FLOOR_SAMPLE_ATTEMPTS = 40,

	WANDER_SAMPLE_COUNT = 28,
	WANDER_PATH_CANDIDATE_LIMIT = 28,
	WANDER_CANDIDATES_PER_SECTOR = 2,
	WANDER_ABSOLUTE_MIN_TARGET_DISTANCE = 3,
	WANDER_MIN_TARGET_DISTANCE = 12,
	WANDER_SHORT_TARGET_PENALTY = 35,
	WANDER_DISTANCE_SCORE_CAP = 120,
	WANDER_FORWARD_WEIGHT = 32,
	WANDER_SCORE_RANDOMNESS = 18,
	WANDER_SECTOR_COUNT = 4,
	WANDER_UNVISITED_SECTOR_BONUS = 500,
	WANDER_REVISIT_RECOVERY_PER_SECOND = 4,
	WANDER_REVISIT_BONUS_CAP = 300,
	TARGET_RESERVATION_RADIUS = 10,
	TARGET_RESERVATION_PROXIMITY_PENALTY = 350,
	TARGET_RESERVATION_SECTOR_PENALTY = 260,

	-- A Hider enters Escape only when it is visible inside the Seeker's forward
	-- search sector (or inside the close 3-stud capture bubble). Normal wandering
	-- does not evaluate Seeker positions at all.
	FLEE_TRIGGER_DISTANCE = 12,
	FLEE_THREAT_CHECK_INTERVAL = 0.2,
	FLEE_RELEASE_DELAY = 0.8,
	FLEE_ROUTE_REPLAN_INTERVAL = 1.25,
	FLEE_DESTINATION_MIN_DISTANCE_GAIN = 5,
	FLEE_DISTANCE_GAIN_SCORE_CAP = 20,
	FLEE_DISTANCE_GAIN_WEIGHT = 24,
	FLEE_DISTANCE_SCORE_CAP = 45,
	FLEE_DISTANCE_WEIGHT = 5,
	FLEE_DANGER_DISTANCE = 12,
	FLEE_DANGER_PENALTY_PER_STUD = 40,
	FLEE_ROUTE_CANDIDATE_LIMIT = 4,
	FLEE_ROUTE_FIRST_GAIN_SCORE_CAP = 12,
	FLEE_ROUTE_FIRST_GAIN_WEIGHT = 30,
	FLEE_ROUTE_DANGER_PENALTY_PER_STUD = 70,
	FLEE_ROUTE_APPROACH_TOLERANCE = 1,

	-- The bot Seeker reacts to short-lived server evidence. It updates a route
	-- only when the evidence point moves meaningfully, never every Heartbeat.
	SEEKER_EVIDENCE_CHECK_INTERVAL = 0.2,
	SEEKER_EVIDENCE_REPLAN_INTERVAL = 0.5,
	SEEKER_EVIDENCE_REPLAN_DISTANCE = 2,

	ROUTE_PREFETCH_DISTANCE = 14,
	PREFETCH_RETRY_SECONDS = 0.35,
	ROUTE_RETRY_SECONDS = 0.1,
	WAYPOINT_REACHED_DISTANCE = 0.42,
	WAYPOINT_PLANE_THRESHOLD = 0.24,
	WAYPOINT_MAX_CROSS_TRACK = 1.25,
	PROGRESS_EPSILON = 0.08,
	STALL_SECONDS = 0.9,

	-- NPCs use the same physical gate proxy as players. When movement stops at
	-- a gate, a small impulse helps the server-owned Humanoid push the moving
	-- leaf instead of endlessly replanning into it.
	DOOR_INTERACTION_DELAY = 0.1,
	DOOR_INTERACTION_MAX_SECONDS = 1.8,
	DOOR_PUSH_INTERVAL = 0.15,
	DOOR_SERVER_OWNERSHIP_SECONDS = 1.25,
	DOOR_PROBE_FORWARD_OFFSET = 0.15,
	-- Includes the 1.5x Seeker proxy radius plus a small contact tolerance.
	DOOR_PROBE_RADIUS = 1.65,
	DOOR_PUSH_CONTACT_DISTANCE = 1.55,
	DOOR_PUSH_SPEED_CHANGE = 1,
	DOOR_PROBE_MAX_PARTS = 16,
})
