--!strict

return table.freeze({
	ROLE_HIDER = "Hider",
	ROLE_SEEKER = "Seeker",
	STARTING_PHASE = "Starting",
	ROUND_PHASE = "Round",
	START_STAGGER_MAX_SECONDS = 0,

	MAP_CONTAINER_NAME = "Map",
	MAP_FLOOR_NAME = "Floor",
	MAP_WALLS_NAME = "Walls",
	MAX_ARENA_DISTANCE = 500,
	MIN_UP_VECTOR_Y = 0.98,
	MIN_GEOMETRY_SIZE = 0.05,
	GEOMETRY_EPSILON = 0.01,

	-- Walls have two mathematical contours. Hard clearance reserves room for
	-- the NPC body; navigation clearance adds a deliberate safety margin.
	BODY_RADIUS = 1.6,
	SAFETY_MARGIN = 0.4,
	NODE_OUTSET = 0.14,
	NODE_MERGE_DISTANCE = 0.06,
	INTERSECTION_OUTSET_DIRECTIONS = 12,
	FLOOR_EDGE_CLEARANCE = 1.6,
	FLOOR_TARGET_EDGE_MARGIN = 1.6,
	FLOOR_SAMPLE_ATTEMPTS = 40,

	WANDER_SAMPLE_COUNT = 28,
	WANDER_PATH_CANDIDATE_LIMIT = 28,
	WANDER_CANDIDATES_PER_SECTOR = 2,
	WANDER_ABSOLUTE_MIN_TARGET_DISTANCE = 3,
	WANDER_MIN_TARGET_DISTANCE = 12,
	WANDER_SHORT_TARGET_PENALTY = 35,
	WANDER_DISTANCE_SCORE_CAP = 120,
	WANDER_FORWARD_WEIGHT = 32,
	WANDER_SCORE_RANDOMNESS = 18,
	WANDER_SECTOR_COUNT = 4,
	WANDER_UNVISITED_SECTOR_BONUS = 500,
	WANDER_REVISIT_RECOVERY_PER_SECOND = 4,
	WANDER_REVISIT_BONUS_CAP = 300,

	ROUTE_PREFETCH_DISTANCE = 14,
	PREFETCH_RETRY_SECONDS = 0.35,
	ROUTE_RETRY_SECONDS = 0.1,
	WAYPOINT_REACHED_DISTANCE = 0.42,
	WAYPOINT_PLANE_THRESHOLD = 0.24,
	WAYPOINT_MAX_CROSS_TRACK = 1.25,
	PROGRESS_EPSILON = 0.08,
	STALL_SECONDS = 0.9,

	-- NPCs keep colliding with hinged gates just like players. When movement
	-- stops at a gate, a small physical impulse helps the server-owned
	-- Humanoid push the moving leaf instead of endlessly replanning into it.
	DOOR_INTERACTION_DELAY = 0.2,
	DOOR_PUSH_INTERVAL = 0.3,
	DOOR_PROBE_FORWARD_OFFSET = 0.35,
	DOOR_PROBE_RADIUS = 2.25,
	DOOR_PUSH_SPEED_CHANGE = 2.5,
	DOOR_PROBE_MAX_PARTS = 16,
})
