--!strict

return table.freeze({
	DATASTORE_NAME = "HideNSeekProfiles_v1",
	DATASTORE_SCOPE = "global",
	DATA_VERSION = 1,
	KEY_PREFIX = "Player_",

	STARTING_CURRENCY = 0,
	MAX_BALANCE = 1_000_000_000_000_000,
	MAX_TRANSACTION = 1_000_000_000_000,

	AUTOSAVE_INTERVAL_SECONDS = 30,
	DIRTY_SAVE_DELAY_SECONDS = 2,
	FAILED_SAVE_RETRY_SECONDS = 5,

	LOAD_ATTEMPTS = 6,
	LOAD_RETRY_DELAY_SECONDS = 2,
	RECONNECT_HANDOFF_WAIT_SECONDS = 10,
	RECONNECT_HANDOFF_POLL_SECONDS = 2,
	PROFILE_LOAD_RETRY_SECONDS = 3,
	PERMANENT_LOAD_RETRY_SECONDS = 30,
	SAVE_ATTEMPTS = 5,
	SAVE_RETRY_BASE_SECONDS = 0.75,
	SAVE_RETRY_MAX_SECONDS = 6,
	SHUTDOWN_DEADLINE_SECONDS = 25,

	ATTR_LOADED = "ProfileLoaded",
	ATTR_LOAD_ERROR = "ProfileLoadError",
	LEADERSTATS_NAME = "leaderstats",
	CURRENCY_VALUE_NAME = "Coins",
})
